### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by carlos-ssh** [AngelUrielFE/basicos-html#1]
**Excelente trabajo hasta ahora.**
Deseable tener:
- TRABAJAR FUTUROS AVANCES DESDE LA RAMA CARACTERISTICAS.
- Trabajar con la estructura basica de HTML
-  Enlazar tu hoja de estilo con tu archivo principal de HTML.

**Happy Coding!**

**_Carlos-SSH_**

**Comment by AngelUrielFE** [comment]
hola buenos dias, trabaje con los cambios requeridos: 
- trabaje en rama caracteristicas.
-  trabaje con la estructura basica html.
- enlace css a los archivos html.

un saludo 
Angel Uriel
